# Generated by Django 5.2.17 on 2026-10-07 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0012_contestparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorker',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kinds', models.JSONField(default=list)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AIContestConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('latest', 'latest'), ('best', 'best')], default='latest', max_length=8)),
                ('private_published', models.BooleanField(default=False)),
                ('practice_enabled', models.BooleanField(default=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='contest.contest')),
            ],
        ),
        migrations.CreateModel(
            name='AIProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('logic', 'logic'), ('model', 'model'), ('challenge', 'challenge')], max_length=16)),
                ('statement', models.JSONField(default=dict)),
                ('cells', models.JSONField(default=list)),
                ('metric', models.CharField(default='Score', max_length=64)),
                ('points', models.PositiveIntegerField(default=100)),
                ('visible', models.BooleanField(default=False)),
                ('judge', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('notebook', 'notebook'), ('evaluation', 'evaluation')], max_length=16)),
                ('official', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=16)),
                ('problem_version', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('source_sha256', models.CharField(max_length=64)),
                ('judge', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=24)),
                ('public_score', models.FloatField(null=True)),
                ('private_score', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('output', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('remote_id', models.PositiveBigIntegerField(null=True)),
                ('dispatch_started', models.BooleanField(default=False)),
                ('worker', models.CharField(blank=True, max_length=64)),
                ('lease', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_studio.aiproblem')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['contest', 'official', 'user'], name='ai_official_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='practice', max_length=32)),
                ('cells', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_studio.aiproblem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'problem', 'scope'), name='ai_draft_scope_unique')],
            },
        ),
        migrations.CreateModel(
            name='AIContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=20)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_problems', to='contest.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_studio.aiproblem')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('contest', 'problem'), name='ai_contest_problem_unique'), models.UniqueConstraint(fields=('contest', 'position'), name='ai_contest_position_unique')],
            },
        ),
    ]
