# Generated by Django 5.2.17 on 2026-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproblem',
            name='public_files',
            field=models.JSONField(default=dict),
        ),
    ]
