# Generated by Django 5.2.17 on 2026-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0002_aiproblem_public_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('paused', models.BooleanField(default=False)),
            ],
        ),
    ]
