"""Real HTTP acceptance using explicitly provisioned, private test sessions.

Never creates users or fabricates grades. Requires five deployed practice tasks,
an administrator followed by fifteen disposable student sessions, and solutions
generated by bootstrap. Creates a password contest, retains records, then hides it.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
import http.cookiejar
import json
from pathlib import Path
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid

ACTIVE = {"PENDING", "RUNNING", "JUDGING", "TRAINING", "SCORING"}


class API:
    def __init__(self, base, session):
        self.base = base.rstrip("/") + "/"
        jar = http.cookiejar.CookieJar()
        self.opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), urllib.request.HTTPCookieProcessor(jar))
        self.headers = {"Cookie": "sessionid=" + session, "Content-Type": "application/json", "Referer": self.base}
        self.call("profile")
        csrf = next(cookie.value for cookie in jar if cookie.name == "csrftoken")
        self.headers["Cookie"] += "; csrftoken=" + csrf
        self.headers["X-CSRFToken"] = csrf

    def call(self, path, method="GET", data=None, fail=False):
        url = self.base + path
        body = None
        if method == "GET" and data:
            url += "?" + urllib.parse.urlencode(data)
        elif method != "GET":
            body = json.dumps(data or {}).encode()
        request = urllib.request.Request(url, data=body, method=method, headers=self.headers)
        result = json.load(self.opener.open(request, timeout=25))
        if fail:
            assert result.get("error"), "Expected request to be rejected: " + path
        else:
            assert not result.get("error"), str(result.get("data"))[:300]
        return result.get("data")

    def submit(self, code, cells, contest=None, kind="evaluation", predictions=None):
        data = {"id": str(uuid.uuid4()), "problem_id": code, "cells": cells, "kind": kind}
        if contest:
            data["contest_id"] = contest
        if predictions is not None:
            data["predictions"] = predictions
        return self.call("ai/jobs", "POST", data)

    def wait(self, job, timeout=900):
        started = time.monotonic()
        while time.monotonic() - started < timeout:
            result = self.call("ai/jobs", data={"id": job["id"]})
            if result["status"] not in ACTIVE:
                return result
            time.sleep(2)
        raise TimeoutError("Job did not finish: " + job["id"])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True, help="OJ URL ending in /api/")
    parser.add_argument("--sessions", type=Path, required=True)
    parser.add_argument("--solutions", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    credentials = json.loads(args.sessions.read_text())
    assert len(credentials) == 16, "Use one administrator and fifteen controlled students"
    clients = [API(args.base, user["session"]) for user in credentials]
    admin, student = clients[:2]
    solutions = {item["id"]: item["cells"] for item in json.loads(args.solutions.read_text())}
    report = {"checks": [], "submissions": []}

    def check(label):
        report["checks"].append(label)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2))
        print(label, flush=True)

    start = datetime.now(timezone.utc) + timedelta(seconds=30)
    end = start + timedelta(minutes=20)
    contest_data = {"title": "AI 20 分钟验收赛 " + start.strftime("%Y%m%d-%H%M%S"),
        "description": "受控测试账号专用，用于真实计时与端到端验收。", "rule_type": "AI", "password": uuid.uuid4().hex[:24],
        "visible": True, "real_time_rank": True, "allowed_ip_ranges": [], "start_time": start.isoformat(), "end_time": end.isoformat()}
    contest = admin.call("admin/contest", "POST", contest_data)
    contest_id = contest["id"]
    report.update({"contest_id": contest_id, "start": start.isoformat(), "end": end.isoformat()})
    config = {"contest_id": contest_id, "selection": "latest", "private_published": False, "practice_enabled": True,
              "problems": [{"id": code, "points": 20} for code in solutions]}
    admin.call("admin/ai/contest", "PUT", config)
    student.call("ai/problems", data={"problem_id": "AI001", "contest_id": contest_id}, fail=True)
    student.call("contest/register", "POST", {"contest_id": contest_id, "password": "incorrect"}, fail=True)
    for client in clients[1:]:
        client.call("contest/register", "POST", {"contest_id": contest_id, "password": contest_data["password"]})
    check("Password registration and pre-start content gate passed")
    while datetime.now(timezone.utc) < start:
        time.sleep(2)
    scope = {"contest_id": contest_id, "problem_id": "AI001"}
    draft = student.call("ai/draft", data=scope)
    student.call("ai/draft", "PUT", {**scope, "cells": solutions["AI001"], "revision": draft["revision"]})
    student.call("ai/draft", "PUT", {**scope, "cells": ["stale"], "revision": draft["revision"]}, fail=True)
    admin.call("admin/ai/contest", "PUT", {**config, "private_published": True}, fail=True)
    admin.call("admin/ai/contest", "PUT", {**config, "selection": "best"}, fail=True)
    student.call("ai/worker", "POST", {"action": "finish", "status": "SCORED", "public_score": 100}, fail=True)
    check("Draft conflict, frozen rules and forged grade rejection passed")
    began = time.monotonic()
    with ThreadPoolExecutor(max_workers=15) as pool:
        submitted = list(pool.map(lambda client: client.submit("AI001", solutions["AI001"], contest_id), clients[1:]))
        report["burst_enqueue_seconds"] = round(time.monotonic() - began, 3)
        finished = list(pool.map(lambda pair: pair[0].wait(pair[1]), zip(clients[1:], submitted)))
    assert all(item["official"] and item["status"] == "ACCEPTED" and item["publicScore"] == 100 for item in finished), [(item["status"], item["publicScore"]) for item in finished]
    report["burst_finish_seconds"] = round(time.monotonic() - began, 3)
    report["submissions"].extend(item["id"] for item in finished)
    check("Fifteen simultaneous submissions completed with independently computed grades")
    for code in ("AI002", "AI003", "AI004", "AI005"):
        csv = None
        if code in ("AI004", "AI005"):
            run = student.wait(student.submit(code, solutions[code], contest_id, kind="notebook"))
            assert run["status"] == "SUCCEEDED", run["status"]
            csv = run["output"]["predictions"]
            assert csv.startswith("id,")
        result = student.wait(student.submit(code, solutions[code], contest_id, predictions=csv))
        assert result["status"] in {"ACCEPTED", "SCORED"} and result["publicScore"] > 50, result["status"]
        assert result["privateScore"] is None
        report["submissions"].append(result["id"])
        check(code + " real Notebook/evaluation flow passed; unpublished private score concealed")
    bad = student.wait(student.submit("AI001", ["import torch\ndef train(X,y,**kwargs):\n    return torch.zeros(2,1), torch.zeros(1)"], contest_id))
    assert bad["status"] == "WRONG_ANSWER" and bad["publicScore"] == 0
    board = student.call("ai/leaderboard", data={"contest_id": contest_id})
    own = next(row for row in board["results"] if row["userId"] == credentials[1]["id"])
    assert own["scores"]["AI001"]["score"] == 0
    check("Incorrect solution rejected; latest submission changes the official score")
    while datetime.now(timezone.utc) <= end:
        assert student.call("ai/health") == {"notebook": True, "evaluation": True}
        time.sleep(min(30, max(1, (end - datetime.now(timezone.utc)).total_seconds())))
    frozen = student.call("ai/leaderboard", data={"contest_id": contest_id})
    practice = student.wait(student.submit("AI001", solutions["AI001"], contest_id))
    assert not practice["official"] and practice["status"] == "ACCEPTED"
    assert student.call("ai/leaderboard", data={"contest_id": contest_id}) == frozen
    admin.call("admin/ai/contest", "PUT", {**config, "private_published": True})
    published = student.call("ai/leaderboard", data={"contest_id": contest_id})
    assert published["privatePublished"]
    for job_id in report["submissions"][-2:]:
        assert student.call("ai/jobs", data={"id": job_id})["privateScore"] is not None
    check("Full twenty-minute window, post-contest practice and private publication passed")
    admin.call("admin/contest", "PUT", {**contest_data, "id": contest_id, "visible": False})
    check("Acceptance contest hidden; evidence retained")


if __name__ == "__main__":
    main()
